name: Build and Deploy Pages

on:
  workflow_dispatch:
  repository_dispatch:
    types: [conch_blessing_updated]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout site repo
        uses: actions/checkout@v4

      - name: Checkout source repo (conch_blessing)
        uses: actions/checkout@v4
        with:
          repository: YOUR_ORG_OR_USER/conch_blessing
          path: source
          token: ${{ secrets.SOURCE_REPO_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install pillow requests beautifulsoup4

      - name: Generate items.js & itemmap.js
        working-directory: source
        run: |
          python3 generate_items_js.py
          python3 build_id_pools.py --itemmap-out itemmap.js

      - name: Prepare site artifact
        run: |
          rm -rf build && mkdir -p build
          cp -v index.html styles.css texts.js script.js favicon.ico build/
          mkdir -p build/resources/gfx/items/collectibles build/resources/gfx/items/trinkets
          rsync -a --delete source/resources/gfx/items/collectibles/ build/resources/gfx/items/collectibles/
          rsync -a --delete source/resources/gfx/items/trinkets/ build/resources/gfx/items/trinkets/
          cp -v source/items.js source/itemmap.js build/

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
